import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import Tabs from "./components/tabs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const years: string[] = Array.from(
    { length: 2026 - 2023 }, // new Date().getFullYear()
    (_, i) => (i + 2024).toString()
  );
  return (
    <html lang="en">
      <body className="antialiased bg-background-img">
        <div className="relative min-h-screen md:flex">
          <Navbar />

          {/* content */}
          <main className="flex-1 h-dvh bg-center bg-cover bg-no-repeat bg-[url('/background.jpg')] bg-slate-500 bg-blend-lighten">
            <div className="px-8 flex justify-center">
              <Tabs contents={years} />
            </div>

            {children}
          </main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
