import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
// import Button from "./components/button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const years: string[] = Array.from(
    { length: 2026 - 2023 }, // new Date().getFullYear()
    (_, i) => (i + 2024).toString()
  );
  return (
    <html lang="en">
      <body className="antialiased bg-background-img">
        <div className="relative min-h-screen md:flex">
          <Navbar />

          {/* content */}
          <main className="flex-1 h-dvh">
            <div className="px-8 flex justify-center">
              {/* {years.map((y: string) => {
                return <Button key={y} title={y} link={"/" + y} />;
              })} */}
            </div>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
